language: python
script: pytest
deploy:
  provider: heroku
  api_key:
    secure: Y5RPPaLEn1kneqoiOIiI1iASycY6C8XNMP31okyH07bHkfsC2u5A6dqeUS2p3J+FrfeE5vEmQEbm+pgeTDb4JqqjjmO798HYXo4CApVsqeurbrR8UBVySXWVKPowHf24AMaa1ylcmRz7tDfAd2kOByoQ6/rLqmT76u10SbQECtfqOjb4XM65Hi21pYJ3Ec0qw0t4tzgPujbyxCZhUW0K5v0mJrlm21FSa6QEvGJ0o2cvA06H8xQVFjraw0Yde24HedYwNjyEZ5ofMf1g4tYqj7sjbpqJFQDH6iIJ4jXvZC1SMHZ4G+grZcQsAkgyiAyw7usPSbKuXoxonQTdwN7dWwqzog+ht795jqibyhEOGqZgI9C79xbGHRYkYOiOqKFeo49fxYpgylb3c9z1vtHhXvp3x7rDod+M7oOf8t3W6TYWJb8XvCdnYUlGs+WbP9H8ez09qqOp1E07naCs52VkBnDWs2uFRrWMpShsUpTJ6MdfL2WXyoRm8I8GONIprN9obaqNHJpLmF2hByION+dbZ9PSCwdkdxmaBJJojpHFAf4lfTvSbbOa2alXBrNPE2plwXv4jm2/nc37bmUaBj4rbbooipiKG12d5g6Sn31fAltoEz9E6DGNFexo0lv08vkfcExgbIFnLkuhNuuQJiEcHszqe9UoEcQgeNPXBGrEV4I=
  app: planning-tool-heroku